import Head from "next/head";
import { getUsers } from "/pages/api/users";

export const getServerSideProps = async () => {
  const users = await getUsers();
  return {
    props: {
      users,
    },
  };
};

export default function Users({ users }) {
  return (
    <div>
      <Head>
        <title>Users Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        {users.map((user, i) => (
          <ul key={i}>
            <li>
              <b> name: </b> {user.name}
            </li>
            <li>
              <b> gender: </b> {user.gender}
            </li>
            <li>
              <b> posts: </b> {JSON.stringify(user["posts"])}
            </li>
          </ul>
        ))}
      </main>
      <footer></footer>
    </div>
  );
}
